#+title: Journals
* [ELSEVIER] MAGNETOSTATICS AND NUMERICAL METHODS
** AEJ - Alexandria Engineering Journal
+ [[https://www.scimagojr.com/journalsearch.php?q=13907&tip=sid&clean=0][Scimago]]
+ [[https://www.journals.elsevier.com/alexandria-engineering-journal?adobe_mc=MCMID%3D64272179754566932943214502000217222347%7CMCORGID%3D4D6368F454EC41940A4C98A6%2540AdobeOrg%7CTS%3D1664207913][Journal page]]

Characteristics:

+ *Q1 (2021)*.
+ *Impact factor:* 6.626.
+ *H-index:* 68.
+ *Cite score:* 8.3.

Alexandria Engineering Journal is an international journal devoted to publishing high quality papers in the field of engineering and applied science. Alexandria Engineering Journal is cited in the Engineering Information Services (EIS) and the Chemical Abstracts (CA). The papers published in Alexandria Engineering Journal are grouped into five sections, according to the following classification:

+ Mechanical, Production, Marine and Textile Engineering.
+ Electrical Engineering, Computer Science and Nuclear Engineering.
+ Civil and Architecture Engineering.
+ Chemical Engineering and Applied Sciences.
+ Environmental Engineering.

Alexandria Engineering Journal publishes original papers, critical reviews, technical papers, technical data, short notes, and letters to the editor. Papers covering experimental, theoretical, and computational aspects which contribute to the understanding of engineering and applied sciences or give an insight into engineering practices and processes are welcome. Authors from all over the world are invited to submit manuscripts for possible publications in Alexandria Engineering Journal.

** Computers & Structures
+ [[https://www.scimagojr.com/journalsearch.php?q=18171&tip=sid&clean=0][Scimago]]
+ [[https://www.sciencedirect.com/journal/computers-and-structures?adobe_mc=MCMID%3D64272179754566932943214502000217222347%7CMCORGID%3D4D6368F454EC41940A4C98A6%2540AdobeOrg%7CTS%3D1664207954][Journal page]]

Characteristics:

+ *Q1 (2021)*.
+ *Impact factor:* 5.372.
+ *H-index:* 144.
+ *Cite score:* 8.2.

Computers & Structures publishes advances in the development and use of computational methods for the solution of problems in engineering and the sciences. The range of appropriate contributions is wide, and includes papers on establishing appropriate mathematical models and their numerical solution in all areas of mechanics. The journal also includes articles that present a substantial review of a field in the topics of the journal. With the modern use of computers and numerical methods to model and solve problems, the traditional boundaries between the fields of solid/structural mechanics and fluid mechanics hardly exist any longer, and multiphysics problems are solved that involve all aspects of mechanics. The word 'structures' must therefore now be interpreted in a broad sense including solids, fluids and multiphysics.
** Mechanics Research Communications
+ [[https://www.scimagojr.com/journalsearch.php?q=17829&tip=sid&clean=0][Scimago]]
+ [[https://www.sciencedirect.com/journal/mechanics-research-communications?adobe_mc=MCMID%3D64272179754566932943214502000217222347%7CMCORGID%3D4D6368F454EC41940A4C98A6%2540AdobeOrg%7CTS%3D1664207967][Journal page]]

Characteristics:

+ *Q1:* Mechanical engineering.
+ *Q2:* Mechanics of materials, Civil and structural engineering, Condensed matter physics.
+ *Impact factor:* 2.749.
+ *H-index:* 71.
+ *Cite score:* 4.4.

Mechanics Research Communications publishes, as rapidly as possible, peer-reviewed manuscripts of high standards but restricted length. It aims to provide:
+ a fast means of communication
+ an exchange of ideas among workers in mechanics
+ an effective method of bringing new results quickly to the public
+ an informal vehicle for the discussion of ideas that may still be in the formative stages

The field of Mechanics will be understood to encompass the behavior of continua, fluids, solids, particles and their mixtures. Submissions must contain a strong, novel contribution to the field of mechanics, and ideally should be focused on current issues in the field involving theoretical, experimental and/or applied research, preferably within the broad expertise encompassed by the Board of Associate Editors. Deviations from these areas should be discussed in advance with the Editor-in-Chief.
** Measurement: Journal of the International Measurement Confederation
+ [[https://www.scimagojr.com/journalsearch.php?q=15424&tip=sid&clean=0][Scimago]]
+ [[https://www.journals.elsevier.com/measurement?adobe_mc=MCMID%3D64272179754566932943214502000217222347%7CMCORGID%3D4D6368F454EC41940A4C98A6%2540AdobeOrg%7CTS%3D1664207976][Journal page]]

Characteristics:

+ *Q1:* Instrumentation, Electrical and electronic engineering, Education, Condensed matter physics, Applied mathematics.
+ *Q2:* Statistics and probability.
+ *Impact factor:* 5.131.
+ *H-index:* 102.
+ *Cite score:* 7.8 .

Contributions are invited on novel achievements in all fields of measurement and instrumentation science and technology. Authors are encouraged to submit novel material, whose ultimate goal is an advancement in the state of the art of: measurement and metrology fundamentals, sensors, measurement instruments, measurement and estimation techniques, measurement data processing and fusion algorithms, evaluation procedures and methodologies for plants and industrial processes, performance analysis of systems, processes and algorithms, mathematical models for measurement-oriented purposes, distributed measurement systems in a connected world.
** Advances in Engineering Software
+ [[https://www.scimagojr.com/journalsearch.php?q=18089&tip=sid&clean=0][Scimago]]
+ [[https://www.sciencedirect.com/journal/advances-in-engineering-software?adobe_mc=MCMID%3D64272179754566932943214502000217222347%7CMCORGID%3D4D6368F454EC41940A4C98A6%2540AdobeOrg%7CTS%3D1664207995][Journal page]]

Characteristics:

+ *Q1:* Engineering (misc.).
+ *Q2:* Software.
+ *Impact factor:* 4.255.
+ *H-index:* 86.
+ *Cite score:* 9.3.

The objective of this journal is to communicate recent and projected advances in computer-based engineering techniques. The fields covered include mechanical, aerospace, civil and environmental engineering, with an emphasis on research and development leading to practical problem-solving. The scope of the journal includes:

+ Innovative computational strategies and numerical algorithms for large-scale engineering problems
+ Analysis and simulation techniques and systems
+ Model and mesh generation
+ Control of the accuracy, stability and efficiency of computational process
+ Exploitation of new computing environments (eg distributed hetergeneous and collaborative computing)
+ Advanced visualization techniques, virtual environments and prototyping
+ Applications of AI, knowledge-based systems, computational intelligence, including fuzzy logic, neural networks and evolutionary computations
+ Application of object-oriented technology to engineering problems
+ Intelligent human computer interfaces
+ Design automation, multidisciplinary design and optimization
+ CAD, CAE and integrated process and product development systems
+ Quality and reliability

The journal publishes research papers, survey papers on key application areas, short communications and technical notes, discussions, software reviews and book reviews. A conference calendar is also included – entries welcome.
** CMAME - Computer Methods in Applied Mechanics and Engineering
+ [[https://www.scimagojr.com/journalsearch.php?q=18158&tip=sid&clean=0][Scimago]]
+ [[https://www.sciencedirect.com/journal/computer-methods-in-applied-mechanics-and-engineering?adobe_mc=MCMID%3D64272179754566932943214502000217222347%7CMCORGID%3D4D6368F454EC41940A4C98A6%2540AdobeOrg%7CTS%3D1664208020][Journal page]]

Characteristics:

+ *Q1 (2021)*
+ *Impact factor:* 6.588.
+ *H-index:* 205.
+ *Cite score:* 10.3.

Computer Methods in Applied Mechanics and Engineering was founded over three decades ago, providing a platform for the publication of papers in this important field of science and engineering. The range of appropriate contributions is very wide. It covers any type of computational method for the simulation of complex physical problems leading to the analysis and design of engineering products and systems. This includes theoretical development and rational applications of mathematical models, variational formulations, and numerical algorithms related to finite element, boundary element, finite difference, finite volume, and meshless discretization methods in the following fields of computational science and engineering:

+ Solid and structural mechanics
+ Fluid mechanics
+ Mechanics of materials
+ Heat transfer
+ Dynamics
+ Geomechanics
+ Acoustics
+ Biomechanics
+ Nanomechanics
+ Molecular dynamics
+ Quantum mechanics
+ Electromagnetics

and also includes virtual design, multiscale phenomena, from nanoscale to macroscale, multiphysics problems, parallel computing, optimization, machine learning, probabilistic and stochastic approaches.

CMAME publishes original papers at the forefront of modern research describing significant developments of computational methods in solving problems of applied mechanics and engineering.
** Engineering Analysis with Boundary Elements
+ [[https://www.scimagojr.com/journalsearch.php?q=20307&tip=sid&clean=0][Scimago]]
+ [[https://www.sciencedirect.com/journal/engineering-analysis-with-boundary-elements][Journal page]]

Characteristics:

+ *Q1:* Engineering.
+ *Q2:* Computational mathematics, Applied mathematics, Analysis.
+ *Impact factor:* 3.25.
+ *H-index:* 77.
+ *Cite score:* 5.0.

This journal is specifically dedicated to the dissemination of the latest developments of new engineering analysis techniques using boundary elements and other mesh reduction methods. Boundary element (BEM) and mesh reduction methods (MRM) are very active areas of research with the techniques being applied to solve increasingly complex problems. The journal stresses the importance of these applications as well as their computational aspects, reliability and robustness. The main criteria for publication will be the originality of the work being reported, its potential usefulness and applications of the methods to new fields. In addition to regular issues, the journal publishes a series of special issues dealing with specific areas of current research. The journal has, for many years, provided a channel of communication between academics and industrial researchers working in mesh reduction methods Fields Covered:

+ Boundary Element Methods (BEM)
+ Mesh Reduction Methods (MRM)
+ Meshless Methods
+ Integral Equations
+ Applications of BEM/MRM in Engineering
+ Numerical Methods related to BEM/MRM
+ Computational Techniques
+ Combination of Different Methods
+ Advanced Formulations
